### ISSUE TITLE
Save timestamp in subtitles

### ISSUE THREAD

**Issue by Martouta** [Martouta/speech_processor#57]
- [x] Add models Duration & RecognitionLine. #/140
- [x] Save timestamp in SRT subtitles (in files) - event empty lines 😂. #138
- [x] Do not save empty lines in subs (SRT files and MongoDB). #141
- [x] [Refactor] Extract Network requests into a Service class. #142
- [x] Save timestamps in MongoDB. #174

**Comment by Martouta** [comment]
Done 🚀
